import { ApolloWrapper, getClient } from '@nx-nextjs-tailwind-storybook/feature'
import './styles.css'
import { PingDocument } from '@nx-nextjs-tailwind-storybook/data-access'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  const { data } = await getClient().query({ query: PingDocument })
  console.log({ data })
  return (
    <html lang={params.lang}>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}
